const defaultExercises = [
  {
    name: 'Hammer Curls',
    type: 'Rep Count',
    quantity: '10',
    category: 'Arms',
  },
  {
    name: 'Preacher Curls',
    type: 'Rep Count',
    quantity: '10',
    category: 'Arms',
  },
  {
    name: 'Tricep Extensions',
    type: 'Rep Count',
    quantity: '10',
    category: 'Arms',
  },
  {
    name: 'Tricep Dips',
    type: 'Rep Count',
    quantity: '20',
    category: 'Arms',
  },
  {
    name: 'Standing Wrist Curl',
    type: 'Rep Count',
    quantity: '15',
    category: 'Arms',
  },
  {
    name: 'Barbell Wrist Curl',
    type: 'Rep Count',
    quantity: '15',
    category: 'Arms',
  },
  {
    name: 'Pull Ups',
    type: 'Rep Count',
    quantity: '10',
    category: 'Back',
  },
  {
    name: 'One Arm Dumbbell Rows',
    type: 'Rep Count',
    quantity: '10',
    category: 'Back',
  },
  {
    name: 'Seated Rows',
    type: 'Rep Count',
    quantity: '10',
    category: 'Back',
  },
  {
    name: 'Lat Pulldowns',
    type: 'Rep Count',
    quantity: '10',
    category: 'Back',
  },
  {
    name: 'Barbell Bench Press',
    type: 'Rep Count',
    quantity: '10',
    category: 'Chest',
  },
  {
    name: 'Dumbbell Flys',
    type: 'Rep Count',
    quantity: '15',
    category: 'Chest',
  },
  {
    name: 'Incline Bench Press',
    type: 'Rep Count',
    quantity: '10',
    category: 'Chest',
  },
  {
    name: 'Push Ups',
    type: 'Rep Count',
    quantity: '10',
    category: 'Chest',
  },
  {
    name: 'Plank',
    type: 'Timed',
    quantity: '60',
    category: 'Core',
  },
  {
    name: 'Sit Ups',
    type: 'Rep Count',
    quantity: '15',
    category: 'Core',
  },
  {
    name: 'V Ups',
    type: 'Rep Count',
    quantity: '10',
    category: 'Core',
  },
  {
    name: 'Bicycles',
    type: 'Rep Count',
    quantity: '10',
    category: 'Core',
  },
  {
    name: 'Hydro Rower',
    type: 'Timed',
    quantity: '120',
    category: 'Full Body',
  },
  {
    name: 'Kettlebell Swings',
    type: 'Rep Count',
    quantity: '15',
    category: 'Full Body',
  },
  {
    name: 'Burpees',
    type: 'Rep Count',
    quantity: '10',
    category: 'Full Body',
  },
  {
    name: 'Squats',
    type: 'Rep Count',
    quantity: '10',
    category: 'Legs',
  },
  {
    name: 'Reverse Lunges',
    type: 'Rep Count',
    quantity: '10',
    category: 'Legs',
  },
  {
    name: 'Hip Bridges',
    type: 'Rep Count',
    quantity: '10',
    category: 'Legs',
  },
  {
    name: 'Lateral Lunges',
    type: 'Rep Count',
    quantity: '10',
    category: 'Legs',
  },
  {
    name: 'Jump Squats',
    type: 'Rep Count',
    quantity: '10',
    category: 'Legs',
  },
  {
    name: 'Pistol Squats',
    type: 'Rep Count',
    quantity: '10',
    category: 'Legs',
  },
  {
    name: 'Leg Extensions',
    type: 'Rep Count',
    quantity: '15',
    category: 'Legs',
  },
  {
    name: 'Leg Curls',
    type: 'Rep Count',
    quantity: '15',
    category: 'Legs',
  },
  {
    name: 'Calf Raises',
    type: 'Rep Count',
    quantity: '15',
    category: 'Legs',
  },
  {
    name: 'Bulgarian Split Squats',
    type: 'Rep Count',
    quantity: '10',
    category: 'Legs',
  },
  {
    name: 'Walking Lunges',
    type: 'Rep Count',
    quantity: '10',
    category: 'Legs',
  },
  {
    name: 'Jump Rope',
    type: 'Timed',
    quantity: '60',
    category: 'Legs',
  },
  {
    name: 'Machine Shoulder Press',
    type: 'Rep Count',
    quantity: '10',
    category: 'Shoulders',
  },
  {
    name: 'Military Press',
    type: 'Rep Count',
    quantity: '10',
    category: 'Shoulders',
  },
  {
    name: 'Dumbbell Lateral Raise',
    type: 'Rep Count',
    quantity: '10',
    category: 'Shoulders',
  },
  {
    name: 'Dumbbell Shrugs',
    type: 'Rep Count',
    quantity: '10',
    category: 'Shoulders',
  },
  {
    name: 'Upright Row',
    type: 'Rep Count',
    quantity: '10',
    category: 'Shoulders',
  },
];

module.exports = defaultExercises;
